name: "CI build"

permissions:
  contents: read
  pull-requests: write

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  
  matrix-build:
    
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    
    steps:

    - name: Install automake (in case of macOS)
      if: runner.os == 'macOS'
      run: |
        brew update
        brew install m4 autoconf automake libtool

    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Generate configure (case Linux or macOS)
      if: runner.os == 'Linux' || runner.os == 'macOS'
      run: autoreconf --install
    
    - name: Build target
      run: |
        chmod +x configure
        ./configure
        make
      shell: bash
    
    - name: Archive executables
      uses: actions/upload-artifact@v4
      with:
        name: binary-${{ matrix.os }}
        path: |
          progres*
          !*.cbp
          !*.c
          !*.h

  build:
    # this is needed to mark green the expected 'build' check,
    # which is a default one in the 'main_basic_rules' ruleset from gh
    runs-on: ubuntu-latest
    needs: matrix-build
    steps:
      - name: All builds passed
        run: echo "All matrix jobs completed successfully."
