name: "CI build"

permissions:
  contents: read
  pull-requests: write

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  
  build:
    
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    
    steps:

    - name: Install automake (in case of macOS)
      if: runner.os == 'macOS'
      run: brew update && brew install m4 autoconf automake libtool

    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Generate configure
      if: runner.os == 'Linux' || runner.os == 'macOS'
      run: autoreconf --install
    
    - name: Build target
      run: |
        ./configure
        make 
    
    - name: Archive executables
      uses: actions/upload-artifact@v4
      with:
        name: binary-${{ matrix.os }}
        path: |
          progres*
          !*.cbp
          !*.c
          !*.h
