name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build target
      run: make

  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install cppunit and lcov
      run: |
        sudo apt-get update
        sudo apt-get install -y libcppunit-dev
        sudo apt-get install -y lcov
    - name: Run tests
      run: |
        cd test
        make coverage
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      with:
        directory: test
        file: coverage.txt
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
