name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build target
      run: make

  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install cppunit 
      run: |
        sudo apt-get update
        sudo apt-get install -y libcppunit-dev
    - name: Run tests
      run: |
        cd test
        make tests
